### ISSUE TITLE
Port to Netstandard2.0?

### ISSUE THREAD

**Issue by solvingj** [autofac/Autofac.Extras.CommonServiceLocator#4] opened 2017-08-17 06:10 UTC
Any chance this library will be ported to Netstandard2.0 since it's out now?

**Comment by tillig** [comment] 2017-08-17 12:07
Duplicate of #3

We can't support anything that CommonServiceLocator itself doesn't support.

**Closed as completed by tillig** 2017-08-17 12:07 UTC

**Comment by tillig** [comment] 2017-09-22 17:53
CommonServiceLocator 1.4 was released with `netstandard2.0` compatibility. [Released compatible Autofac.Extras.CommonServiceLocator 4.1.0.](https://www.nuget.org/packages/Autofac.Extras.CommonServiceLocator/4.1.0)

**Comment by solvingj** [comment] 2017-09-22 19:09
I really appreciate you posting this here for posterity!
